{ pkgs, ... }:
{
  users.users.alina.packages = with pkgs; [
    monero-gui
    beets
    dualsensectl
    swww
    linux-wallpaperengine
    nicotine-plus
    calcure
    electrum
    bytecode-viewer
    freecad
    blender
    zed-editor
    wireshark
    mpv
    mpvpaper
    pinentry-qt
    tor-browser
    krita
    librewolf
    element-desktop
    android-file-transfer
    kitty
    bluez
    keepassxc
    noisetorch
    prismlauncher
    qbittorrent
    signal-desktop-bin
    standardnotes
    telegram-desktop
    thunderbird
    ungoogled-chromium
    virt-manager
    wireplumber
    zathura
    dolphin-emu
    inkscape
  ];
}
