{pkgs, ...}: {
    users.users.alina.packages = with pkgs; [
      gcc
      imhex
      aha
      apktool
      zola
      jadx
      mdbook
      jujutsu
      dotnetCorePackages.dotnet_9.sdk
      nuget-to-json
      kind
      go
      docker
      docker-compose
      buildah
      podman
      nixpacks
      podman
      flyctl
      cachix
      git
      checksec
      wfuzz
      binwalk
      colmena
      apktool
      rustup
      cargo-expand
      #chntpw
      fnm
      rustup
      sccache
      radare2
      android-tools
      gdb
      apktool
      libnotify
      godot_4
      #jdk8
      #jdk21
      #jdk17
      nginx
      ansible
      python3
      nurl
      nix-init
      bubblewrap
    ];
}
