{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    spicetify-cli
    spotify-player
    sptlrx
    mopidy-spotify
    spot
    psst
    spotube
    spotdl
    mopidy-iris
    mopidy
    beatprints
    gnomeExtensions.mpris-label
    spotify
    aria2
    nix-tree
    calendar-cli
    syncthingtray
    kdePackages.dolphin
    signal-cli
    feather
    xmrig
    qbittorrent-cli
    qbittorrent-enhanced-nox
    niri
    stardust-xr-kiara
    sq
    basilk
    taskwarrior3
    kdePackages.kdenlive
    kdePackages.yakuake
    kdePackages.spectacle
    kdePackages.taglib
    darktable
    stc-cli
    llvmPackages_21.bintools
    syncthing
    blender
    lnav
    toolong
    peertube
    haskell.compiler.native-bignum.ghcHEAD
    (postgresql_18_jit.withPackages (ext: with ext; [
      ip4r # IPv4/v6 and IPv4/v6 range index type for PostgreSQL
      pgtap # Unit testing framework for PostgreSQL
      pgjwt # PostgreSQL implementation of JSON Web Tokens
      pgddl # DDL eXtractor functions for PostgreSQL
      repmgr # Replication manager for PostgreSQL cluster
      #pg_net # Async networking for Postgres
      pg_ivm # Materialized views with IVM (Incremental View Maintenance) for PostgreSQL
      pg_csv # Flexible CSV processing for Postgres
      hypopg # Hypothetical Indexes for PostgreSQL
      postgis # Geographic Objects for PostgreSQL
      pgrouting # geospatial routing for PostGIS
      audit # Open Source PostgreSQL Audit Logging
      pg_topn # Efficient querying of 'top values' for PostgreSQL
      periods # PostgreSQL extension implementing SQL standard functionality for PERIODs and SYSTEM VERSIONING
      wal2json # PostgreSQL JSON output plugin for changeset extraction
      #pgx_ulid # Universally Unique Lexicographically Sortable Identifiers
      pgsodium # Modern cryptography using libsodium
      pg_uuidv7 # version 7 UUIDs
      pg-semver # Semantic version data type for PostgreSQL
      pg_repack # Reorganize tables in PostgreSQL databases with minimal locks
      pg_squeeze # PostgreSQL extension for automatic bloat cleanup
      #pg_ed25519 # PostgreSQL extension for signing and verifying ed25519 signatures
      #vectorchord # Scalable, fast, and disk-friendly vector search in Postgres, the successor of pgvecto.rs
      #timescaledb # Scales PostgreSQL for time-series data via automatic partitioning across time and space
      pg_relusage # discover and log the relations used in your statements
      temporal_tables # Temporal Tables PostgreSQL Extension
      #pg_auto_failover # PostgreSQL extension and service for automated failover and high-availability
    ]))
    p7zip
    bettercap
    monero-cli
    hydroxide
    vikunja
    protonmail-bridge
    ausweisapp
    prosody
    jitsi
    jitsi-excalidraw
    excalidraw_export
    jitsi-videobridge
    jitsi-meet-prosody
    prometheus-jitsi-exporter
    prometheus
    grafterm
    grafana
    grafana-loki
    grafana-alloy
    mimir
    python3
    kubernetes
    kubernetes-kcp
    kubernetes-validate
    kubernetes-polaris
    opentofu
    ansible
    jenkins-job-builder
    jcli
    snicat
    sniproxy
    haproxy
    kubernetes-helm-wrapped
    jenkins
    ejabberd
    bat-extras.core
    networkminer
    networkd-notify
    networkmanager-vpnc
    networkmanager-sstp
    networkmanager-l2tp
    networkmanagerapplet
    networkmanager_dmenu
    networkmanager-openvpn
    linux-router
    bird2
    bird3
    pw-viz
    wayfarer
    pw-volume
    pa-notify
    coppwr
    gnomecast
    gnome-usage
    bird-lg
    containerlab
    lxc
    jool-cli
    nftables
    #frr
    #servo
    burpsuite
    web-ext
    firefox
    knot-dns
    knot-resolver
    dnsdist
    kea
    wireshark
    immich
    keycloak
    wl-mirror
    waypipe
    pidgin
    typstyle
    tinymist
    sequoia-wot
    sequoia-sq
    sequoia-sqv
    sequoia-sqop
    sequoia-chameleon-gnupg
    qpwgraph
    pwvucontrol
    qjackctl
    easyeffects
    helvum
    zstd
    unzip
    ouch
    tlp
    acpid
    lm_sensors
    irssi
    catgirl
    iamb
    pinentry
    yubikey-manager
    tomb
    ssh-to-age
    sops
    monero-gui
    beets
    dualsensectl
    swww
    linux-wallpaperengine
    nicotine-plus
    #calcure
    electrum
    bytecode-viewer
    freecad
    blender
    zed-editor
    mpv
    mpvpaper
    pinentry-qt
    tor-browser
    krita
    librewolf
    android-file-transfer
    kitty
    bluez
    keepassxc
    noisetorch
    prismlauncher
    qbittorrent
    signal-desktop-bin
    standardnotes
    telegram-desktop
    thunderbird
    ungoogled-chromium
    virt-manager
    wireplumber
    zathura
    dolphin-emu
    inkscape
    gcc
    sad
    rustc
    cargo
    flatpak
    pixiecore
    erlang_28
    podman
    k9s
    k3d
    k3s
    #imhex
    kubectl
    eza
    zoxide
    aha
    apktool
    zola
    jadx
    mdbook
    jujutsu
    dotnetCorePackages.dotnet_9.sdk
    nuget-to-json
    kind
    go
    docker
    docker-compose
    buildah
    podman
    nixpacks
    podman
    flyctl
    cachix
    git
    checksec
    wfuzz
    binwalk
    colmena
    apktool
    cargo-expand
    fnm
    sccache
    radare2
    android-tools
    gdb
    apktool
    libnotify
    godot_4
    nginx
    ansible
    nurl
    nix-init
    du-dust
    btrfs-progs
    inotify-tools
    glow
    fd
    tree
    lsd
    kdePackages.kdeconnect-kde
    bat
    hexyl
    lsof
    ranger
    rsync
    usbutils
    flac
    taskwarrior3
    tldr
    fastfetch
    typst
    texliveSmall
    btop
    htop
    powertop
    blahaj
    jq
    file
    imagemagick
    pferd
    hyfetch
    appimage-run
    tmate
    tmux
    zellij
    which
    upower
    viu
    doas
    sdparm
    nvme-cli
    less
    man-db
    man-pages
    lshw
    pciutils
    acpid
    tlp
    hdparm
    strace
    nix-output-monitor
    languagetool
    woeusb
    ffmpeg
    exif
    pango
    fontconfig
    proxychains
    croc
    rclone
    magic-wormhole-rs
    inetutils
    tcpdump
    termshark
    tidal-dl
    tor
    wireguard-tools
    mtr
    nmap
    netcat
    sshfs
    subfinder
    tshark
    dnsutils
    ldns
    doggo
    yt-dlp
    yggdrasil
    traceroute
    lynx
    elinks
    w3m
    wget
    curl
    slskd
    checksec
    procyon
    cfr
    frida-tools
    apktool
    binwalk
    thc-hydra
    john
    metasploit
    sherlock
    radare2
    sslsplit
    subfinder
  ];
}
