source ~/infra/nu/links.nu
source ~/infra/nu/deploy.nu
source ~/infra/nu/dme.nu
source ~/infra/nu/flacInfo.nu
source ~/infra/nu/jj-nu-log.nu
source ~/infra/nu/l.nu
source ~/infra/nu/mp.nu
source ~/infra/nu/net.nu
source ~/infra/nu/nre.nu
source ~/infra/nu/sortHome.nu
source ~/infra/nu/trains.nu
source ~/infra/nu/update.nu
source ~/infra/nu/dl.nu
