{
    imports = [
	./bird-lg.nix
	./home-assistant.nix
	./restic.nix
	./knot.nix
	./vaultwarden.nix
	./jellyfin.nix 
	./conduwuit.nix 
	./firefox-sync.nix 
	./excalidraw.nix 
	./invidious.nix 
	./iceshrimp.nix 
	./librenms.nix 
	./nixos-cache.nix 
	./hydra.nix 
	./grafana.nix
	./magnetico.nix 
	./matrix-bridge-discord.nix 
	./matrix-bridge-signal.nix 
	./matrix-bridge-telegram.nix 
	./matrix-bridge-whatsapp.nix 
	./mail-server.nix 
	./nautobot.nix 
	./netbox.nix 
	./nextcloud.nix 
	./outline.nix 
	./paperless.nix 
	./peertube.nix 
	./photoprism.nix 
	./gitlab.nix 
	./qbittorrent.nix 
	./searx.nix 
	./tor-relay.nix 
	./keycloak.nix 
	./kanidm.nix
    ];
}
