source ./src.nu
source ./status.nu
source ./dirs.nu
source ./weh.nu
source ./wp.nu
source ./meta.nu
source ./direnv.nu
source ./links.nu
source ./doc.nu
source ./deploy.nu
source ./dme.nu
source ./flacInfo.nu
source ./jj-nu-log.nu
source ./l.nu
source ./mp.nu
source ./net.nu
source ./nre.nu
source ./sortHome.nu
source ./trains.nu
source ./dl.nu
